services:
  - type: web
    name: chat-app
    runtime: node
    rootDir: ./
    buildCommand: |
      echo "Building frontend..."
      cd frontend
      npm install
      npm run build
      echo "Installing backend dependencies..."
      cd ../backend
      npm install --production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.0
      - key: PORT
        fromDatabase:
          name: port
          property: port
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false